{% set name = "googledrivedownloader" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b565a454945506a32370b0c9a47731bd2ac9701159e3dfe262d194d4d60f4cbc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - requests

test:
  imports:
    - google_drive_downloader

about:
  home: https://pypi.org/project/googledrivedownloader/
  summary: Minimal class to download shared files from Google Drive.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - ndmaxar
    - oblute
